package chat_bot_projesi;


import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author açt
 */
public class chat_ekrani extends javax.swing.JFrame {
     List<Phone> t; List<pc> b; Tweet yeni;
    ArrayList<String> exceptionMessageList = new
    ArrayList<String>(Arrays.asList(" Anlasilmadi ! Lutfen tekrarlar misin ?"));
    ArrayList<String> greetingMessageList = new ArrayList<String>(Arrays.asList("ooo selammm..", "merhabalar", "mrb","slm"));
    ArrayList<String> halhatirMessageList = new ArrayList<String>(Arrays.asList("iyidir senden?", "tessekkur ederim siz?","Tesekkurler, iyiyim. siz?"));
    ArrayList<String> urunler = new ArrayList<String>(Arrays.asList(" 1.Telefon 2.Bilgisayar"));
    public chat_ekrani( List<Phone> t,List<pc> b, Tweet yeni) {
        this.t=t; this.b=b; this.yeni=yeni;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtEnter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtChat.setColumns(20);
        txtChat.setRows(5);
        txtChat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtChatPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(txtChat);

        jLabel1.setText("                CHAT BOT");

        txtEnter.setText("jTextField1");
        txtEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterActionPerformed(evt);
            }
        });
        txtEnter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtEnterPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(txtEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtChatPropertyChange
           txtChat.setEditable(false);
           txtChat.setForeground(Color.RED);
           txtChat.setBackground(Color.BLACK);
           
    }//GEN-LAST:event_txtChatPropertyChange

    private void txtEnterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtEnterPropertyChange
           txtEnter.requestFocusInWindow();
           Font font = new Font("Arial", Font.ITALIC, 14);
           txtEnter.setFont(font);
           txtEnter.setForeground(Color.RED);
           txtEnter.setText("");
    }//GEN-LAST:event_txtEnterPropertyChange

    private void txtEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterActionPerformed
        String uText = txtEnter.getText();
        txtChat.append("\n Siz : " + uText + "\n");
        txtEnter.setText("");
        if (uText.contains("selam")||uText.contains("merhaba")||uText.contains("merhabalar")) 
            decideRandom(greetingMessageList);
        else if(uText.contains("naber")||uText.contains("nasilsiniz"))
            decideRandom(halhatirMessageList); 
        else if(uText.contains("urun secmek istiyorum")||uText.contains("urun"))
              urunler();
         else if(uText.contains("1"))
              try {
                  telefon_urunler();
        } catch (IOException ex) {
            Logger.getLogger(chat_ekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(uText.contains("2"))
              try {
                  pc_urunler();
        } catch (IOException ex) {
            Logger.getLogger(chat_ekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
            decideRandom(exceptionMessageList);

    }//GEN-LAST:event_txtEnterActionPerformed
   
    private void decideRandom(ArrayList<String> messageList) {
        int decider = (int) (Math.random() * messageList.size());
        txtChat.append("\t\t" + messageList.get(decider));
    }
     private void urunler()
     {
         txtChat.append("\t\t" + urunler.get(0));
     }
    private void telefon_urunler() throws IOException
    {   double kiyas=0.0; int yeri=0; double x;
        for(int i =0 ; i<this.t.size();i++)
        { x=yeni.get_TweetPolarity(t.get(i).getModel());
         if(kiyas<x)
        {yeri=i; kiyas=x;}
         txtChat.append("\n\n"+(i+1) +"\n"+ t.get(i).ToString()+ "\n Polarity degerleri : "+x+ "\n En cok like alan tweet : "+yeni.getBest_tweet(t.get(i).getModel()));   }
            
      txtChat.append("\n\n\t Polarity En Yuksek Model\n\n"+(yeri+1) +"\n"+ t.get(yeri).ToString()+ "\n Polarity degerleri : "+kiyas+ "\n En cok like alan tweet : "+yeni.getBest_tweet(t.get(yeri).getModel()));   
    }
     private void pc_urunler() throws IOException
     {double kiyas=0.0; int yeri=0; double x;
        for(int i =0 ; i<this.b.size();i++)
        { x=yeni.get_TweetPolarity(b.get(i).getModel());
         if(kiyas<x)
        {yeri=i; kiyas=x;}
         txtChat.append("\n\n"+(i+1) +"\n"+ b.get(i).ToString()+ "\n Polarity degerleri : "+x+ "\n En cok like alan tweet : "+yeni.getBest_tweet(b.get(i).getModel()));   }
            
      txtChat.append("\n\n\t Polarity En Yuksek Model\n\n"+(yeri+1) +"\n"+ b.get(yeri).ToString()+ "\n Polarity degerleri : "+kiyas+ "\n En cok like alan tweet : "+yeni.getBest_tweet(b.get(yeri).getModel()));  }
     
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtEnter;
    // End of variables declaration//GEN-END:variables
}
